### ISSUE TITLE
crash during twingate_resource update for bad alias value

### ISSUE THREAD

**Issue by builtroller** [Twingate/terraform-provider-twingate#552]
Terraform Version: 1.8.5
twingate provider version: 3.0.5

I was attempting to make a simple change to an existing `twingate_resource`. 
- update the `name`
- add an `alias`

Here is the relevant portion of the plan:
```tf
  # twingate_resource.core80 will be updated in-place
  ~ resource "twingate_resource" "core80" {
      + alias                       = "dev-platform-core-us-east-1"
        id                          = "UmVzb3VyY2U6MjUxMzIxOQ=="
      ~ name                        = "dev-platform-core-us-east-1" -> "db-dev-platform-core-us-east-1"
        # (8 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

And here is the error:
```tf
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-twingate_v3.0.5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86539a]

goroutine 16 [running]:
github.com/Twingate/terraform-provider-twingate/v3/twingate/internal/provider/resource.(*twingateResource).Update(0xc00006a548, {0xdf6fc8, 0xc00034e990}, {{{{0xdfbfd0, 0xc0003bbdd0}, {0xbb7e80, 0xc0003a7470}}, {0xdfe010, 0xc00053a870}}, {{{0xdfbfd0, ...}, ...}, ...}, ...}, ...)
	github.com/Twingate/terraform-provider-twingate/v3/twingate/internal/provider/resource/resource.go:833 +0x63a
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).UpdateResource(0xc00032a000, {0xdf6fc8, 0xc00034e990}, 0xc0005ab510, 0xc0005ab4e8)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_updateresource.go:122 +0x6ee
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0xc00032a000, {0xdf6fc8, 0xc00034e990}, 0xc00053a500, 0xc0005ab6d0)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/fwserver/server_applyresourcechange.go:102 +0x192
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0xc00032a000, {0xdf6fc8?, 0xc00034e840?}, 0xc00053a370)
	github.com/hashicorp/terraform-plugin-framework@v1.9.0/internal/proto6server/server_applyresourcechange.go:55 +0x38e
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0xc00016e0a0, {0xdf6fc8?, 0xc0001538f0?}, 0xc0001e6620)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x3d0
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0xc97e20, 0xc00016e0a0}, {0xdf6fc8, 0xc0001538f0}, 0xc000017580, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000326000, {0xdf6fc8, 0xc000153380}, {0xdfcc00, 0xc000362000}, 0xc000570b40, 0xc000153ad0, 0x134c5f8, 0x0)
	google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
google.golang.org/grpc.(*Server).handleStream(0xc000326000, {0xdfcc00, 0xc000362000}, 0xc000570b40)
	google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 26
	google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

Error: The terraform-provider-twingate_v3.0.5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

After destroying the resource, and recreating I received the actual error. I was trying to use a single label domain. Here is the error after recreating the resource:

```tf
╷
│ Error: failed to create twingate_resource
│ 
│   with twingate_resource.core80,
│   on rds_instance_core.tf line 78, in resource "twingate_resource" "core80":
│   78: resource "twingate_resource" "core80" {
│ 
│ failed to create resource: Alias must be a valid DNS name
╵
```

Ultimately this was a problem on my side with providing a bad `alias`, but in my original configuration the change caused the plugin to crash rather than providing me with the correct error message.

**Comment by ekampf** [comment]
Thanks for the report @builtroller 👍 
This should be fixed with the latst `v3.0.6` release
